import { model, Schema } from "mongoose";
import { TReferences, ReferenceModel } from "./references.interface";

const referenceSchema = new Schema<TReferences>(
  {
    slug: {
      type: String,
      required: false,  // Auto-generated by pre-save middleware
      trim: true,
      unique: true,
    },
    type: {
      type: String,
      enum: ["book", "article", "hadith", "quran"],
      required: true,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    author: {
      type: String,
      trim: true,
    },
    citationText: {
      type: String,
      trim: true,
    },
    sourceUrl: {
      type: String,
      trim: true,
    },
    sourceLanguage: {
      type: String,
      trim: true,
    },
    verified: {
      type: Boolean,
      default: false,
    },
    verifiedBy: {
      type: Schema.Types.ObjectId,
      ref: "User",
    },
    createdBy:{
      type: Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
  },
  {
    timestamps: true,
    versionKey: false,
  }
);

referenceSchema.index({ type: 1 });
referenceSchema.index({ verified: 1 });
referenceSchema.index({ createdAt: -1 });

referenceSchema.pre("save", async function (next) {
  // Prevent slug modification on existing documents
  if (!this.isNew && this.isModified("slug")) {
    throw new Error(
      "Slug cannot be modified after creation."
    );
  }

  if (!this.slug && this.isNew) {
    // Generate SEO-friendly slug from title
    let baseSlug = this.title
      .toLowerCase()
      .trim()
      .replace(/[^\w\s-]/g, '')      // Remove special characters
      .replace(/\s+/g, '-')           // Replace spaces with hyphens
      .replace(/-+/g, '-')            // Multiple hyphens to single
      .replace(/^-|-$/g, '')          // Trim hyphens from edges
      .substring(0, 60);              // Limit length
    
    // Ensure uniqueness with database check
    this.slug = baseSlug;
    let counter = 1;
    const maxRetries = 100;
    
    while (counter < maxRetries) {
      const exists = await Reference.findOne({ slug: this.slug }).select('_id').lean();
      if (!exists) break;
      this.slug = `${baseSlug}-${counter}`;
      counter++;
    }
    
    // Fallback to timestamp if needed
    if (counter >= maxRetries) {
      this.slug = `${baseSlug}-${Date.now()}`;
    }
  }
  next();
});

referenceSchema.statics.isExistBySlug = async function (slug: string) {
  return this.findOne({ slug });
};

export const Reference = model<TReferences, ReferenceModel>(
  "Reference",
  referenceSchema,
  "references"
);
